#!/bin/sh /etc/rc.common

START=60

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/oui-httpd
    procd_append_param command -p 80
    procd_append_param command --rpc /usr/lib/oui-httpd/rpc
    procd_append_param command --home /www
    procd_append_param command --index "oui.html"
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "oui-httpd"
}
