#
# Copyright (C) 2019 Jianhui Zhao <zhaojh329@gmail.com>
#
# This is free software, licensed under the MIT.
#

include $(TOPDIR)/rules.mk

APP_TITLE:=Oui Support for rtty

include ../../oui.mk

# call BuildPackage - OpenWrt buildroot signature
