#
# Copyright (C) 2022 Jianhui Zhao <zhaojh329@gmail.com>
#
# This is free software, licensed under the MIT.
#

include $(TOPDIR)/rules.mk

APP_TITLE:=Stations
APP_NAME:=stations
APP_DEPENDS:=+lua-eco-nl80211 +lua-eco-ubus

include ../../oui.mk

# call BuildPackage - OpenWrt buildroot signature
