#
# Copyright (C) 2019 Jianhui Zhao <zhaojh329@gmail.com>
#
# This is free software, licensed under the MIT.
#

include $(TOPDIR)/rules.mk

APP_TITLE:=System Setting

include ../../oui-app.mk

# call BuildPackage - OpenWrt buildroot signature
